name: Deploy Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare site directory
        run: |
          rm -rf public_site
          mkdir -p public_site
          cp -r soapcr.com/* public_site/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
